accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('signup/', views.signup, name = 'signup'),
    path('login/', views.login, name = 'login'),
    path('logout/', views.logout, name = 'logout'),
    path('delete/', views.delete, name = 'delete'),
    path('update/', views.update, name = 'update'),
    path('update/password_change/', views.password_change, name = 'password_change'),
    path('follow/<int:user_pk>/', views.follow, name = 'follow'),

]

instagram/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from accounts import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('', views.index),    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

posts/urls.py
from django.urls import path
from . import views

app_name="posts"
urlpatterns = [
    path('create/', views.create, name="create"),
    path('update/<int:post_id>/', views.update, name="update"),
    path('delete/<int:post_id>/', views.delete, name="delete"),
    path('like/<int:post_id>/', views.like, name="like"),
    path('createcomment/<int:post_id>/', views.createcomment, name="createcomment"),
]

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='followings')

posts/models.py
from django.db import models
from django.conf import settings
# from django.contrib.auth.model import User  // 이거 사용하지 않는 이유 ?

from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFill, ResizeToFit, Thumbnail
# ResizeToFill : 300*300 자르는 것(crop)
# ResizeToFit : 가장 긴 곳(너비/높이)을 300으로 맞추고, 비율에 맞춰서


# Create your models here.
class Post(models.Model):
    content = models.TextField()
    image=models.ImageField()
    image_thumbnail = ImageSpecField(source='image',
                        processors=[Thumbnail(300, 300)],
                        format='JPEG',
                        options={'quality': 60})
    # 원본 잘라서 저장 : ProcessedImageField
    # image = ProcessedImageField(
    #                       processors=[ResizeToFill(100, 50)],
    #                       format='JPEG',
    #                       options={'quality': 60})

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) 
    like_user = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')
    created_at = models.DateTimeField(auto_now_add=True)
    created_at = models.DateTimeField(auto_now =True)

    

class Comment(models.Model):
    content = models.CharField( max_length=300)
    created_at = models.DateTimeField(auto_now_add=True)
    created_at = models.DateTimeField(auto_now =True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) 
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm,UserCreationForm

# 그대로 활용하지 못하는 경우는 항상 상속받아서 custom!!!!
class CustomUserChangeForm(UserChangeForm):
    first_name = forms.CharField(
        max_length=20,
        label = '이름',
        help_text = '이름을 입력하세요',
        widget= forms.TextInput(
            attrs={
                'placeholder': '이름 입력'
            }
        )
    )
    
    class Meta:
        model = get_user_model()
        fields = ['username', 'first_name', 'last_name', 'email']


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields= ['username']

accounts/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth import get_user_model #회원가입 유저/
from django.contrib.auth.forms import AuthenticationForm,PasswordChangeForm #로그인 form
from django.contrib.auth import login as auth_login #로그인 정보 세션에 저장
from django.contrib.auth import logout as auth_logout

from django.contrib import messages
from django.contrib.auth import update_session_auth_hash

from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.db.models import Count, Prefetch

from .forms import CustomUserChangeForm, CustomUserCreationForm


from posts.models import Post, Comment
from posts.forms import CommentForm

User = get_user_model() # 유저 Import

# Create your views here.
def index(request):
    accounts = User.objects.all()
    # posts = Post.objects.all()
    # posts = Post.objects.prefetch_related('comment_set').order_by('-pk')
    # 2) 사용자 이름
    # posts = Post.objects.select_related('user').order_by('-pk')
    # 3) 댓글 목록
    # posts = Post.objects.prefetch_related('comment_set').order_by('-pk')

    posts = Post.objects.prefetch_related(
        	Prefetch(
        	    'comment_set',
    		    queryset=Comment.objects.select_related('user')
		    )
    	).order_by('-pk')

    commentform = CommentForm()
    context ={
       'accounts': accounts,
       'posts': posts,
       'commentform':commentform
    }
    return render(request, 'accounts/index.html',context)

def signup(request):
    if request.user.is_authenticated:
        return redirect('accounts:index')

    if request.method =='POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('accounts:index')

    form = CustomUserCreationForm()
    context={
        'form':form
    }
    return render(request, 'accounts/form.html',context)


def login(request):
    if request.method == 'POST':
            form = AuthenticationForm(request, request.POST)
            if form.is_valid():
                auth_login(request, form.get_user()) # Session을 생성하면서 Session Id를 부여
                return redirect(request.GET.get('next') or 'accounts:index')
    else:
        form = AuthenticationForm()
    context ={
        'form' : form
    }
    return render(request,'accounts/form.html', context)

@login_required
def logout(request):
    auth_logout(request)
    return redirect('accounts:index')

@login_required
@require_POST
def delete(request):
    request.user.delete()
    return redirect ('accounts:index')

def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form
    }
    return render(request, 'accounts/update.html', context)

@login_required
def password_change(request):
    if request.method == "POST":
        form = PasswordChangeForm(user = request.user, data=request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important! 로그인 상태 유지.
            messages.success(request, 'Your password was successfully updated!')
            return redirect('accounts:index')
    else:
        form = PasswordChangeForm(user = request.user)
    context ={
        'form':form
    }
    return render(request,'accounts/update.html',context)

@login_required
def follow(request, user_pk):
    user = get_object_or_404(User, pk=user_pk)
    if request.user == user:
        return redirect('accounts:index')
    else:
        if user.followers.filter(pk = request.user.id).exists():
            user.followers.remove(request.user)
        else:
            user.followers.add(request.user)

        
        return redirect('accounts:index')

accounts/templates/accounts/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block content %}
<div class="row justify-content-center mt-5">

<form action="" method='POST'> {% csrf_token %}
    {% bootstrap_form form %}
    <button type ='submit'> 제출
    </button>
</form>

</div>
{% endblock content %}

accounts/templates/accounts/index.html
{% extends 'base.html' %}

{% block content %}
<h1>시작페이지</h1>
<div class='row'>
    
    <div class='col-md-8 text-center'>
        {% for post in posts %}
            <div>
                <span>{{post.user.username}}</span>
                {% if request.user in post.user.followers.all  %}
                    <a href="{% url 'accounts:follow' post.user.id %}"> 팔로우취소</a>
                {% else %}
                    <a href="{% url 'accounts:follow' post.user.id %}"> 팔로우</a>
                {% endif %}
            </div>
            <img src="{{ post.image_thumbnail.url }}">
            <p>{{post.content}}</p>
            <a href="{% url 'posts:update' post.id %}">디테일</a>
            <br>
            {% for comment in post.comment_set.all %}
                {{comment.user}} : {{comment.content}}
            {% empty%} 
                <p>없음</p> 
            {% endfor %}

            {% if request.user in post.like_user.all %}
                <div> <a href="{% url 'posts:like' post.id %}">좋아요 취소</a></div>
            {% else %}
                <div> <a href="{% url 'posts:like' post.id %}">좋아요</a></div>
            {% endif %}
            <form action="{% url 'posts:createcomment' post.id %}" method="POST" class='mb-5'>
                {% csrf_token %}
                    {{commentform}}
                    <button>제출</button>
            </form>
        {% empty %}
            <h1>없음</h1>
        {% endfor %}
    </div>
    
    
    <div class='col-md-4'>
        <div class='bg-block'>{{request.user}}</div>
        <div>스토리 </div>
        <div>회원님을 위한 추천 </div>
    </div>

</div>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<a href="{% url 'posts:create' %}"> 글쓰기</a>

{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% load bootstrap4 %}
{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button class="btn btn-primary">수정</button>
    </form>
    <a href="{% url 'accounts:password_change' %}">비번</a>
{% endblock %}