accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('signup/', views.signup, name = 'signup'),
    path('login/', views.login, name = 'login'),
    path('logout/', views.logout, name = 'logout'),
    path('delete/', views.delete, name = 'delete'),
    path('update/', views.update, name = 'update'),
    path('update/password_change/', views.password_change, name = 'password_change'),
    path('follow/<int:user_pk>/', views.follow, name = 'follow'),

]

instagram/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from accounts import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('', views.index),    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

posts/urls.py
from django.urls import path
from . import views

app_name="posts"
urlpatterns = [
    path('create/', views.create, name="create"),
    path('update/<int:post_id>/', views.update, name="update"),
    path('delete/<int:post_id>/', views.delete, name="delete"),
    path('like/<int:post_id>/', views.like, name="like"),
    path('createcomment/<int:post_id>/', views.createcomment, name="createcomment"),
]

templates/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% bootstrap_css %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'accounts:index'%}">Instagram</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link active" href="{% url 'accounts:index'%}">Home</a>
                {% if request.user.is_authenticated %}
                    welcome {{request.user.username}}
                <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
                <a class="nav-item nav-link" href="{% url 'accounts:update' %}"> 회원정보 수정</a>
                {% else %}
                <a class="nav-item nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
                <a class="nav-item nav-link" href="{% url 'accounts:login' %}">로그인</a>
                {% endif %}
            </div>
        </div>
    </nav>
    
    <div class ='container'>
    {% block content %}
    {% endblock content%}
    </div>
</body>

</html>